### ISSUE TITLE
Add package for wrapping underlined text correctly

### ISSUE THREAD

**Issue by polyfeux** [DirkRusche/LaTeX#10]
To my surprise a simple command like underlining a longer passage (in my case: in a `\todo[inline]{foo}`-box) is not that easy in Latex, because the underlined passage will not be wrapped at the end of line; see here: https://tex.stackexchange.com/q/9550.

The package [ulem](https://ctan.org/pkg/ulem) takes care of this issue.
It is important to use it with the following parameter, so it [does not mix up](https://texfaq.org/FAQ-underline) `\emph`:
`\usepackage[normalem]{ulem}`

Usage in a tex-file: `\uline{foo}`

**Comment by DirkRusche** [comment]
Do we need underlining in the basic template?

At the moment I can't see a use case for the template. Can you clear things up? :relaxed:

**Comment by polyfeux** [comment]
Yeah, you are right. I was just so confused that this little thing seemed to need such an effort to be solved.

You can close this issue and I am just going to keep this special procedure for underlining text in mind.
