### ISSUE TITLE
packages.sty: biblatex backend-parameter wrong

### ISSUE THREAD

**Issue by polyfeux** [DirkRusche/LaTeX#5]
While in the packages.sty file the parameter for the biblatex `backend ` is set to `bibtex`, my editor TeXstudio runs sometimes into some kind of endless loop when trying to compile. While with `backend=biber` it runs just fine.

Is this a general issue or just me?

**Comment by DirkRusche** [comment]
Can you report further information?

- Which operating system do you use?
- When does this occure? After the first compilation (no temporary tex files exist in the directory) or after recompiling?
- Any error message after aborting the process?

**Comment by polyfeux** [comment]
It's fine now - I installed the current version of TexLive (2018 instead of 2016) and the current version of TeXstudio.

Thank you for your assistance, you can close this issue.
